import Head from "next/head";
import ReposView from "../components/repos/ReposView/ReposView";
import subDays from "date-fns/subDays";
import format from "date-fns/format";
import { NextPageWithLayout } from "./_app";
import DefaultLayout from "../components/layouts/default";

const Home: NextPageWithLayout = () => {
  const weekAgo = format(subDays(new Date(), 7), "yyyy-MM-dd");

  return (
    <>
      <Head>
        <title>Github Code Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 gap-10 md:grid-cols-2 md:grid-rows-1">
        <ReposView title={"Trending This Week"} created={weekAgo} />
        <ReposView title={"Popular"} stars={1000} />
      </div>
    </>
  );
};

Home.getLayout = function (page) {
  return <DefaultLayout>{page}</DefaultLayout>;
};

export default Home;
