import type { NextPage } from "next";
import Head from "next/head";
import AppHeader from "../components/common/AppHeader/AppHeader";
import withDefaultGithubClient from "../utils/withUrqlGithubClient";
import TrendingReposView from "../components/repos/TrendingReposView/TrendingReposView";

const Home: NextPage = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Github Code Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppHeader title={"GitHub Code Viewer"} caption={"Fast and quick"} />
        <TrendingReposView />
      </main>
    </div>
  );
};

export default withDefaultGithubClient(Home);
